services:
  frontend:
      build: ./frontend
      container_name: tech_frontend
      ports:
        - "8080:80"
      depends_on:
        - backend

  backend:
    build: ./backend
    container_name: tech_backend
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_started
    environment:
        - SPRING_MONGODB_URI=mongodb://admin:password123@mongodb:27017/tech_hardware_db?authSource=admin
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tech_hardware_db

  postgres:
    image: postgres:15-alpine
    container_name: tech_postgres
    restart: always
    environment:
      POSTGRES_USER: admin           # id (test)
      POSTGRES_PASSWORD: password123 # mdp (test)
      POSTGRES_DB: tech_hardware_db 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      # Utilise l'utilitaire standard pg_isready
      test: ["CMD-SHELL", "pg_isready -U admin -d tech_hardware_db"]
      interval: 5s
      timeout: 3s       
      retries: 5         
      start_period: 10s 

  mongodb:
    image: mongo:5.0
    container_name: tech_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin       
      MONGO_INITDB_ROOT_PASSWORD: password123 
      MONGO_INITDB_DATABASE: tech_hardware_db
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: