services:
  frontend:
      build: ./frontend
      container_name: tech_frontend
      ports:
        - "8080:80"
      depends_on:
        - postgres

  postgres:
    image: postgres:15-alpine
    container_name: tech_postgres
    restart: always
    environment:
      POSTGRES_USER: admin           # id (test)
      POSTGRES_PASSWORD: password123 # mdp (test)
      POSTGRES_DB: tech_hardware_db 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: